### ISSUE TITLE
Change syntax to remove "sär skrivning" (grammar ftw)

### ISSUE THREAD

**Issue by magnusdahlstrand** [johnie/postcss-swedish-stylesheets#4]
I suggest the following changes to the syntax, because grammar:

| From | To |
| --- | --- |
| bakgrund-färg | bakgrundsfärg |
| bakgrund-bild | bakgrundsbild |
| typsnitt-familj | typsnittsfamilj |
| linje-höjd | radhöjd |
| bokstav-mellanrum | bokstavsmellanrum |

Observe the change from "linje" to "rad" as well.

:hamster:

**Comment by johnie** [comment]
Du har en poäng. Har länge funderat på att göra om dem. Får bli i nästa Major! :bowtie:
